export const SKILL_IMAGE_BY_ID: Record<string, string> = {
  javascript: "/images/javascript.webp",
  next: "/images/next.webp",
  typeScript: "/images/typescript.webp",
  zustand: "/images/zustand.webp",
  react: "/images/react.webp",
  reactQuery: "/images/react-query.webp",
  sass: "/images/sass.webp",
  jest: "/images/jest.webp",
  cypress: "/images/cypress.webp",
  storybook: "/images/storybook.webp",
  styledComponents: "/images/styled-components.webp",
  vue: "/images/vue.webp",
  pinia: "/images/pinia.webp",
  chartJs: "/images/chartjs.webp",
  websocket: "/images/websocket.webp",
  recoil: "/images/recoil.webp",
  rxJs: "/images/rxjs.webp",
  d3: "/images/d3.webp",
  highcharts: "/images/highcharts.webp",
  reduxToolkit: "/images/redux-toolkit.webp",
  vuex: "/images/vuex.webp",
};
